import { SaasProduct } from './types';

export const saasProducts: SaasProduct[] = [
  {
    id: 1,
    name: 'Slack',
    category: 'Communication',
    description: 'Slack is a messaging app for business that connects people to the information they need.',
    priceMonthly: 8.75,
    priceYearly: 87.50,
    freePlan: true,
    trialDays: 0,
    features: [
      'Real-time messaging',
      'File sharing',
      'Integrations with 2000+ apps',
      'Video and voice calls',
      'Searchable message history',
    ],
    websiteUrl: 'https://slack.com',
    logoUrl: 'https://cdn.brandfetch.io/idVfYwcuQz/theme/dark/symbol.svg',
    rating: 4.5,
    pros: ['Excellent integrations', 'Intuitive UI', 'Great mobile apps'],
    cons: ['Can be expensive', 'Notifications overwhelming'],
    targetUsers: 'Teams, Remote workers, Startups',
  },
  {
    id: 2,
    name: 'Salesforce',
    category: 'CRM',
    description: 'The world\'s #1 CRM platform for sales, service, marketing, and more.',
    priceMonthly: 25,
    priceYearly: 300,
    freePlan: false,
    trialDays: 30,
    features: [
      'Contact management',
      'Opportunity management',
      'Sales forecasting',
      'Workflow automation',
      'AI-powered insights',
    ],
    websiteUrl: 'https://www.salesforce.com',
    logoUrl: 'https://cdn.brandfetch.io/idTCJo-F7s/theme/dark/symbol.svg',
    rating: 4.3,
    pros: ['Highly customizable', 'Extensive ecosystem', 'Powerful reporting'],
    cons: ['Steep learning curve', 'Expensive'],
    targetUsers: 'Enterprise, Sales teams',
  },
  {
    id: 3,
    name: 'Asana',
    category: 'Project Management',
    description: 'A web and mobile work management platform to help teams organize and track work.',
    priceMonthly: 10.99,
    priceYearly: 131.88,
    freePlan: true,
    trialDays: 30,
    features: [
      'Task management',
      'Project timelines',
      'Workload management',
      'Custom fields',
      '100+ integrations',
    ],
    websiteUrl: 'https://asana.com',
    logoUrl: 'https://cdn.brandfetch.io/idJ5Bv-_Uz/theme/dark/symbol.svg',
    rating: 4.4,
    pros: ['Beautiful interface', 'Flexible views', 'Strong collaboration'],
    cons: ['Limited reporting in free plan', 'No time tracking'],
    targetUsers: 'Project managers, Teams, Agencies',
  },
  {
    id: 4,
    name: 'HubSpot CRM',
    category: 'CRM',
    description: 'A free CRM platform with all the tools you need to attract and engage customers.',
    priceMonthly: 0,
    priceYearly: 0,
    freePlan: true,
    trialDays: 0,
    features: [
      'Contact management',
      'Deal pipeline',
      'Email tracking',
      'Meeting scheduling',
      'Live chat',
    ],
    websiteUrl: 'https://www.hubspot.com/products/crm',
    logoUrl: 'https://cdn.brandfetch.io/idnrCPuv87/theme/dark/symbol.svg',
    rating: 4.5,
    pros: ['Completely free CRM', 'Easy to use', 'Great email integration'],
    cons: ['Advanced features require paid plans', 'Can get expensive'],
    targetUsers: 'Small businesses, Startups',
  },
  {
    id: 5,
    name: 'Notion',
    category: 'Project Management',
    description: 'An all-in-one workspace for notes, docs, project management, and collaboration.',
    priceMonthly: 8,
    priceYearly: 96,
    freePlan: true,
    trialDays: 0,
    features: [
      'Notes and docs',
      'Databases',
      'Kanban boards',
      'Real-time collaboration',
      'API access',
    ],
    websiteUrl: 'https://www.notion.so',
    logoUrl: 'https://cdn.brandfetch.io/id2S8jp36N/theme/dark/symbol.svg',
    rating: 4.6,
    pros: ['Extremely flexible', 'Beautiful design', 'Great for knowledge management'],
    cons: ['Steep learning curve', 'Limited offline'],
    targetUsers: 'Teams, Individuals, Knowledge workers',
  },
  {
    id: 6,
    name: 'Zoom',
    category: 'Communication',
    description: 'A video communications platform for conferencing, meetings, and webinars.',
    priceMonthly: 15.99,
    priceYearly: 159.90,
    freePlan: true,
    trialDays: 0,
    features: [
      'HD video meetings',
      'Screen sharing',
      'Recording',
      'Breakout rooms',
      'Virtual backgrounds',
    ],
    websiteUrl: 'https://zoom.us',
    logoUrl: 'https://cdn.brandfetch.io/idtDmTcT7D/theme/dark/symbol.svg',
    rating: 4.4,
    pros: ['Reliable quality', 'Easy to use', 'Works on any device'],
    cons: ['40-min limit on free', 'Security concerns'],
    targetUsers: 'Remote teams, Educators, Everyone',
  },
  {
    id: 7,
    name: 'QuickBooks',
    category: 'Accounting',
    description: 'Accounting software for small businesses to manage finances and invoicing.',
    priceMonthly: 30,
    priceYearly: 360,
    freePlan: false,
    trialDays: 30,
    features: [
      'Invoicing',
      'Expense tracking',
      'Bank connections',
      'Financial reports',
      'Tax preparation',
    ],
    websiteUrl: 'https://quickbooks.intuit.com',
    logoUrl: 'https://cdn.brandfetch.io/idAP_bvT6K/theme/dark/symbol.svg',
    rating: 4.2,
    pros: ['Industry standard', 'Comprehensive features', 'Good mobile app'],
    cons: ['Can be expensive', 'Learning curve'],
    targetUsers: 'Small businesses, Freelancers',
  },
  {
    id: 8,
    name: 'Figma',
    category: 'Design',
    description: 'A collaborative interface design tool for creating, prototyping, and gathering feedback.',
    priceMonthly: 15,
    priceYearly: 144,
    freePlan: true,
    trialDays: 0,
    features: [
      'Vector editing',
      'Prototyping',
      'Real-time collaboration',
      'Design systems',
      'Developer handoff',
    ],
    websiteUrl: 'https://www.figma.com',
    logoUrl: 'https://cdn.brandfetch.io/idZHcZ_i7F/theme/dark/symbol.svg',
    rating: 4.7,
    pros: ['Best collaboration', 'Browser-based', 'Great prototyping'],
    cons: ['Requires internet', 'Can lag with large files'],
    targetUsers: 'Designers, Product teams, Agencies',
  },
  {
    id: 9,
    name: 'Zendesk',
    category: 'Customer Support',
    description: 'Customer service software and support ticket system for better customer relationships.',
    priceMonthly: 49,
    priceYearly: 588,
    freePlan: false,
    trialDays: 14,
    features: [
      'Ticketing system',
      'Live chat',
      'Knowledge base',
      'Analytics',
      'AI-powered bots',
    ],
    websiteUrl: 'https://www.zendesk.com',
    logoUrl: 'https://cdn.brandfetch.io/idFNr-wVU_/theme/dark/symbol.svg',
    rating: 4.3,
    pros: ['Comprehensive solution', 'Excellent analytics', 'Scalable'],
    cons: ['Can be expensive', 'Complex setup'],
    targetUsers: 'Support teams, Enterprise',
  },
  {
    id: 10,
    name: 'GitHub',
    category: 'Development',
    description: 'A developer platform for creating, storing, and managing code with Git version control.',
    priceMonthly: 4,
    priceYearly: 48,
    freePlan: true,
    trialDays: 0,
    features: [
      'Git repositories',
      'Pull requests',
      'Code review',
      'Actions (CI/CD)',
      'Copilot AI',
    ],
    websiteUrl: 'https://github.com',
    logoUrl: 'https://cdn.brandfetch.io/idZAyF9rlg/theme/dark/symbol.svg',
    rating: 4.8,
    pros: ['Industry standard', 'Excellent collaboration', 'Powerful CI/CD'],
    cons: ['Private repos limited in free', 'Complex for beginners'],
    targetUsers: 'Developers, Open source projects',
  },
];

export function getProductById(id: number): SaasProduct | undefined {
  return saasProducts.find(p => p.id === id);
}

export function getProductsByCategory(category: string): SaasProduct[] {
  if (category === 'All') return saasProducts;
  return saasProducts.filter(p => p.category === category);
}

export function getProductsByIds(ids: number[]): SaasProduct[] {
  return saasProducts.filter(p => ids.includes(p.id));
}
